import { useEffect, useMemo, useState } from "react";
import {
  deleteAdminUser,
  inviteAdminUser,
  listAdminUsers,
  sendPasswordReset,
  updateAdminUser,
} from "../services/adminUsersApi";
import { updateCurrentAdminPassword } from "../services/adminAuth";

const emptyInvite = {
  email: "",
  displayName: "",
  role: "admin",
};

export function UsersModule({ currentUserEmail }) {
  const [users, setUsers] = useState([]);
  const [currentAdmin, setCurrentAdmin] = useState(null);
  const [inviteDraft, setInviteDraft] = useState(emptyInvite);
  const [passwordDraft, setPasswordDraft] = useState("");
  const [inviteOpen, setInviteOpen] = useState(false);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState("");

  const canManageUsers = useMemo(
    () => currentAdmin?.is_super_admin || currentAdmin?.role === "owner",
    [currentAdmin],
  );

  useEffect(() => {
    loadUsers();
  }, []);

  async function loadUsers() {
    setLoading(true);
    const result = await listAdminUsers();
    setUsers(result.users);
    setCurrentAdmin(result.currentAdmin);
    setMessage(result.error || "");
    setLoading(false);
  }

  async function handleInvite(event) {
    event.preventDefault();
    setSaving(true);
    setMessage("");

    const result = await inviteAdminUser(inviteDraft);
    if (result.error) {
      setMessage(result.error);
    } else {
      setInviteDraft(emptyInvite);
      setInviteOpen(false);
      setMessage("Invitation sent and admin profile saved.");
      await loadUsers();
    }

    setSaving(false);
  }

  async function handleUserUpdate(user, patch) {
    setSaving(true);
    const result = await updateAdminUser(user.id, patch);
    setMessage(result.error || "User updated.");
    if (!result.error) await loadUsers();
    setSaving(false);
  }

  async function handleDelete(user) {
    const confirmed = window.confirm(`Remove admin access for ${user.email}?`);
    if (!confirmed) return;

    setSaving(true);
    const result = await deleteAdminUser(user.id);
    setMessage(result.error || "Admin access removed.");
    if (!result.error) await loadUsers();
    setSaving(false);
  }

  async function handleResetPassword(user) {
    setSaving(true);
    const result = await sendPasswordReset(user.email);
    setMessage(result.error || "Password reset link generated by Supabase.");
    setSaving(false);
  }

  async function handleOwnPasswordChange(event) {
    event.preventDefault();
    setSaving(true);
    const result = await updateCurrentAdminPassword(passwordDraft);
    setMessage(result.error || "Your password was updated.");
    if (!result.error) setPasswordDraft("");
    setSaving(false);
  }

  return (
    <section className="admin-module-stack">
      <div className="admin-white-panel admin-users-panel">
        <div className="admin-section-heading">
          <div>
            <h3>Admin users</h3>
            <p>Invite users, set roles and control who can manage the panel.</p>
          </div>
          {canManageUsers ? (
            <button
              className="admin-primary-light"
              type="button"
              onClick={() => setInviteOpen((isOpen) => !isOpen)}
            >
              {inviteOpen ? "Close" : "New user"}
            </button>
          ) : null}
        </div>

        {message ? <p className="admin-inline-message">{message}</p> : null}

        {inviteOpen && canManageUsers ? (
          <form className="admin-editor-drawer" onSubmit={handleInvite}>
            <div className="admin-form-grid">
              <label>
                Email
                <input
                  value={inviteDraft.email}
                  onChange={(event) =>
                    setInviteDraft({ ...inviteDraft, email: event.target.value })
                  }
                  placeholder="artist@example.com"
                />
              </label>
              <label>
                Display name
                <input
                  value={inviteDraft.displayName}
                  onChange={(event) =>
                    setInviteDraft({ ...inviteDraft, displayName: event.target.value })
                  }
                  placeholder="Artist name"
                />
              </label>
              <label>
                Role
                <select
                  value={inviteDraft.role}
                  onChange={(event) =>
                    setInviteDraft({ ...inviteDraft, role: event.target.value })
                  }
                >
                  <option value="admin">Admin</option>
                  <option value="owner">Owner</option>
                  <option value="viewer">Viewer</option>
                </select>
              </label>
            </div>
            <button className="admin-primary-light" disabled={saving} type="submit">
              {saving ? "Sending..." : "Send invite"}
            </button>
          </form>
        ) : null}

        <div className="admin-users-table">
          {loading ? <p className="admin-muted-light">Loading users...</p> : null}
          {users.map((user) => (
            <article className="admin-user-row" key={user.id}>
              <div>
                <strong>{user.display_name || user.email}</strong>
                <span>{user.email}</span>
                <small>
                  {user.last_sign_in_at
                    ? `Last login ${new Date(user.last_sign_in_at).toLocaleDateString()}`
                    : "No login recorded yet"}
                </small>
              </div>
              <AdminRoleBadge role={user.role} active={user.is_active} />
              <div className="admin-user-actions">
                {canManageUsers ? (
                  <>
                    <select
                      value={user.role}
                      onChange={(event) => handleUserUpdate(user, { role: event.target.value })}
                    >
                      <option value="owner">Owner</option>
                      <option value="admin">Admin</option>
                      <option value="viewer">Viewer</option>
                    </select>
                    <button
                      className="admin-light-button"
                      disabled={saving || user.email === currentUserEmail}
                      type="button"
                      onClick={() => handleUserUpdate(user, { is_active: !user.is_active })}
                    >
                      {user.is_active ? "Disable" : "Enable"}
                    </button>
                    <button
                      className="admin-light-button"
                      disabled={saving}
                      type="button"
                      onClick={() => handleResetPassword(user)}
                    >
                      Reset password
                    </button>
                    <button
                      className="admin-light-button admin-delete-button"
                      disabled={saving || user.email === currentUserEmail}
                      type="button"
                      onClick={() => handleDelete(user)}
                    >
                      Remove
                    </button>
                  </>
                ) : (
                  <span className="admin-muted-light">Owner access required</span>
                )}
              </div>
            </article>
          ))}
        </div>
      </div>

      <div className="admin-white-panel admin-users-panel">
        <div className="admin-section-heading">
          <div>
            <h3>Change my password</h3>
            <p>Update the password for your own logged-in account.</p>
          </div>
        </div>
        <form className="admin-password-form" onSubmit={handleOwnPasswordChange}>
          <label>
            New password
            <input
              minLength="8"
              type="password"
              value={passwordDraft}
              onChange={(event) => setPasswordDraft(event.target.value)}
              placeholder="At least 8 characters"
            />
          </label>
          <button className="admin-primary-light" disabled={saving || passwordDraft.length < 8} type="submit">
            Update password
          </button>
        </form>
      </div>
    </section>
  );
}

function AdminRoleBadge({ active, role }) {
  return (
    <span className={`admin-role-badge admin-role-badge--${role} ${active ? "" : "is-disabled"}`}>
      {active ? role : "disabled"}
    </span>
  );
}
