-- Editable form copy: every English string used on the public tattoo form,
-- paired with its Hebrew translation, editable from the admin "Texts" module.

create table if not exists public.form_texts (
  key text primary key,
  en_text text not null,
  he_text text not null,
  updated_at timestamptz not null default now()
);

drop trigger if exists set_form_texts_updated_at on public.form_texts;
create trigger set_form_texts_updated_at
before update on public.form_texts
for each row execute function public.set_updated_at();

alter table public.form_texts enable row level security;

create policy "Public can read form texts"
on public.form_texts for select
to anon, authenticated
using (true);

create policy "Admin editors can manage form texts"
on public.form_texts for all
to authenticated
using (public.can_manage_admin_content())
with check (public.can_manage_admin_content());

insert into public.form_texts (key, en_text, he_text)
values
  ('brand', 'Zen House Tattoo', 'Zen House Tattoo'),
  ('intro', 'Design request', 'בקשת עיצוב'),
  ('step', 'Step', 'שלב'),
  ('of', 'of', 'מתוך'),
  ('back', 'Back', 'חזרה'),
  ('next', 'Next', 'הבא'),
  ('quote', 'Send request', 'שליחת פנייה'),
  ('clearAll', 'Clear marks', 'ניקוי סימונים'),
  ('delete', 'Delete', 'מחיקה'),
  ('mark', 'Mark', 'סימון'),
  ('marksEmpty', 'No marks yet.', 'אין סימונים עדיין.'),
  ('referenceImages', 'Reference images', 'תמונות השראה'),
  ('maxReferenceImages', 'Up to 4 images', 'עד 4 תמונות'),
  ('maxPlacementBoxes', 'Up to 3 marks', 'עד 3 סימונים'),
  ('minIdeaCharacters', 'Minimum 20 characters', 'מינימום 20 תווים'),
  ('moreStyles', 'More styles', 'עוד סגנונות'),
  ('showLessStyles', 'Show less', 'הצג פחות'),
  ('otherStyleNeedsReference', 'For Other style, please upload at least one reference image.', 'לסגנון אחר מומלץ לצרף לפחות תמונת השראה אחת.'),
  ('submitting', 'Redirecting you to WhatsApp...', 'מעבירים אתכם לוואטסאפ...'),
  ('steps.name.title', 'Welcome', 'ברוכים הבאים'),
  ('steps.name.note', 'So we can send you a quote for the perfect tattoo, please fill in the details below.', 'כדי שנוכל לשלוח לכם הצעת מחיר לקעקוע המושלם אנא מלאו את הפרטים הבאים'),
  ('steps.name.placeholders.fullName', 'Full name', 'שם מלא'),
  ('steps.name.placeholders.email', 'Email', 'אימייל'),
  ('steps.name.placeholders.phone', 'WhatsApp number', 'מספר טלפון'),
  ('steps.description.title', 'Tell us about the tattoo', 'ספרו לנו על הקעקוע'),
  ('steps.description.ideaLabel', 'Tattoo description', 'תיאור הקעקוע'),
  ('steps.description.uploadLabel', 'Up to 4 images allowed', 'ניתן להעלות עד 4 תמונות בלבד'),
  ('steps.description.placeholder', 'Describe the idea, size, mood or important details...', 'תארו בקצרה את הרעיון, הגודל, האווירה או פרטים חשובים...'),
  ('steps.color.title', 'Which do you prefer?', 'מה תעדיפו?'),
  ('steps.style.title', 'What style speaks to you?', 'איזה סטייל מדבר אליכם?'),
  ('steps.bodyReference.title', 'Which model should we place the tattoo on?', 'על איזה מודל נמקם את הקעקוע?'),
  ('steps.generalZone.title', 'Choose a category', 'בחירת אזור'),
  ('steps.specificZone.title', 'Please choose the area', 'אנא בחרו את האיזור'),
  ('steps.placement.title', 'Mark the tattoo placement', 'סימון מיקום הקעקוע'),
  ('steps.placement.note', 'Please mark the area where you''d like the tattoo.', 'אנא סמנו את האיזור שבו תרצו את הקעקוע'),
  ('steps.timing.title', 'When are you planning to get tattooed?', 'מתי תכננתם להתקעקע?'),
  ('steps.contactTime.title', 'What is the best time to reach you?', 'מתי נוח לכם לדבר?'),
  ('steps.contactTime.note', 'You can choose more than one option.', 'אפשר לבחור יותר מאפשרות אחת.'),
  ('steps.hasTattoos.title', 'Do you already have tattoos?', 'האם התקעקעתם בעבר?'),
  ('options.male', 'Male', 'גבר'),
  ('options.female', 'Female', 'אישה'),
  ('options.yes', 'Yes', 'כן'),
  ('options.no', 'No', 'לא'),
  ('options.torso', 'Torso', 'טורסו'),
  ('options.arm', 'Arm', 'זרוע'),
  ('options.leg', 'Leg', 'רגל'),
  ('options.hand', 'Hand', 'כף יד'),
  ('options.face', 'Face / neck', 'פנים / צוואר'),
  ('options.torsoFront', 'Torso front', 'קדמת הטורסו'),
  ('options.torsoBack', 'Torso back', 'גב הטורסו'),
  ('options.torsoRibs', 'Ribs', 'צלעות'),
  ('options.armInner', 'Inner arm', 'פנים הזרוע'),
  ('options.armOuter', 'Outer arm', 'חוץ הזרוע'),
  ('options.sleeve', 'Sleeve', 'שרוול'),
  ('options.legsFront', 'Legs front', 'קדמת הרגליים'),
  ('options.legBack', 'Leg back', 'אחורי הרגל'),
  ('options.legSide', 'Leg side', 'צד הרגל'),
  ('options.handInner', 'Palm side', 'כף היד'),
  ('options.handOuter', 'Top of hand', 'גב כף היד'),
  ('options.faceFront', 'Front', 'קדמי'),
  ('options.faceBack', 'Back', 'אחורי'),
  ('options.faceSide', 'Side', 'צד'),
  ('options.fineLine', 'Fine line', 'קו דק'),
  ('options.realism', 'Realism', 'ריאליזם'),
  ('options.newAge', 'New age', 'ניו אייג׳'),
  ('options.traditional', 'Old school', 'אולד סקול'),
  ('options.japanese', 'Japanese', 'יפני'),
  ('options.blackwork', 'Blackwork', 'בלאקוורק'),
  ('options.geometric', 'Geometric', 'גיאומטרי'),
  ('options.biomechanical', 'Biomechanical', 'ביומכני'),
  ('options.chicano', 'Chicano', 'צ''יקאנו'),
  ('options.futuristic', 'Futuristic', 'עתידני'),
  ('options.lettering', 'Lettering', 'לטרינג'),
  ('options.dotwork', 'Dotwork', 'דוטוורק'),
  ('options.microRealism', 'Micro realism', 'מיקרו ריאליזם'),
  ('options.abstract', 'Abstract', 'אבסטרקט'),
  ('options.floral', 'Floral', 'פרחוני'),
  ('options.mandala', 'Mandala', 'מנדלה'),
  ('options.neoTraditional', 'Neo traditional', 'נאו מסורתי'),
  ('options.newSchool', 'New school', 'ניו סקול'),
  ('options.ornamental', 'Ornamental', 'אורנמנטלי'),
  ('options.portrait', 'Portrait', 'פורטרט'),
  ('options.sketch', 'Sketch', 'סקיצה'),
  ('options.surrealism', 'Surrealism', 'סוריאליזם'),
  ('options.trashPolka', 'Trash polka', 'טראש פולקה'),
  ('options.tribal', 'Tribal', 'טרייבל'),
  ('options.watercolor', 'Watercolor', 'צבעי מים'),
  ('options.other', 'Other', 'אחר'),
  ('options.blackGrey', 'Black & grey', 'שחור ואפור'),
  ('options.color', 'Color', 'צבע'),
  ('options.now', 'ASAP', 'בהקדם האפשרי'),
  ('options.weeks', 'Next weeks', 'בשבועיים הקרובים'),
  ('options.month', 'Next month', 'בחודש הקרוב'),
  ('options.dontCare', 'I don''t care', 'לא משנה לי'),
  ('options.morning', 'Morning ☀', '☀ בוקר'),
  ('options.afternoon', 'Afternoon ◐', '◐ צהריים'),
  ('options.night', 'Night ☾', '☾ ערב'),
  ('errors.name', 'Add your name, email and WhatsApp number.', 'יש למלא שם, אימייל ומספר WhatsApp.'),
  ('errors.description', 'Write at least 20 characters.', 'יש לכתוב לפחות 20 תווים.'),
  ('errors.style', 'Choose a style.', 'יש לבחור סגנון.'),
  ('errors.color', 'Choose a color option.', 'יש לבחור צבע.'),
  ('errors.bodyReference', 'Choose a body reference.', 'יש לבחור ייחוס גוף.'),
  ('errors.generalZone', 'Choose a body area.', 'יש לבחור אזור בגוף.'),
  ('errors.specificZone', 'Choose a specific view.', 'יש לבחור זווית ספציפית.'),
  ('errors.placement', 'Draw at least one placement mark.', 'יש לסמן לפחות מיקום אחד.'),
  ('errors.timing', 'Choose when you want to do it.', 'יש לבחור מתי תרצו לעשות את הקעקוע.'),
  ('errors.contactTime', 'Choose the best time to contact you.', 'יש לבחור זמן נוח ליצירת קשר.'),
  ('errors.hasTattoos', 'Choose yes or no.', 'יש לבחור כן או לא.'),
  ('errors.default', 'Complete this step to continue.', 'יש להשלים את השלב כדי להמשיך.'),
  ('whatsapp.hello', 'Hi ZenHouse! I want to request a tattoo.', 'שלום ZenHouse! אשמח לקבל הצעת מחיר לקעקוע.'),
  ('whatsapp.name', 'Name', 'שם'),
  ('whatsapp.email', 'Email', 'אימייל'),
  ('whatsapp.phone', 'Phone', 'טלפון'),
  ('whatsapp.bodyReference', 'Body reference', 'ייחוס גוף'),
  ('whatsapp.hasTattoos', 'Has tattoos?', 'יש קעקועים?'),
  ('whatsapp.generalZone', 'Category', 'אזור'),
  ('whatsapp.specificZone', 'View', 'זווית'),
  ('whatsapp.placement', 'Placement', 'סימון'),
  ('whatsapp.style', 'Style', 'סגנון'),
  ('whatsapp.color', 'Color', 'צבע'),
  ('whatsapp.idea', 'Idea', 'רעיון'),
  ('whatsapp.referenceImages', 'Reference images', 'תמונות השראה'),
  ('whatsapp.timing', 'When', 'מתי'),
  ('whatsapp.contactTime', 'Contact time', 'זמן קשר')
on conflict (key) do nothing;
