-- Keep Text Management focused on fixed copy only.
-- Dynamic labels for styles and body photos are managed from their own admin modules.

delete from public.form_texts
where key in (
  'otherStyleNeedsReference',
  'options.male',
  'options.female',
  'options.torso',
  'options.arm',
  'options.leg',
  'options.hand',
  'options.face',
  'options.torsoFront',
  'options.torsoBack',
  'options.torsoRibs',
  'options.armInner',
  'options.armOuter',
  'options.sleeve',
  'options.legsFront',
  'options.legBack',
  'options.legSide',
  'options.handInner',
  'options.handOuter',
  'options.faceFront',
  'options.faceBack',
  'options.faceSide',
  'options.fineLine',
  'options.realism',
  'options.newAge',
  'options.traditional',
  'options.japanese',
  'options.blackwork',
  'options.geometric',
  'options.biomechanical',
  'options.chicano',
  'options.futuristic',
  'options.lettering',
  'options.dotwork',
  'options.microRealism',
  'options.abstract',
  'options.floral',
  'options.mandala',
  'options.neoTraditional',
  'options.newSchool',
  'options.ornamental',
  'options.portrait',
  'options.sketch',
  'options.surrealism',
  'options.trashPolka',
  'options.tribal',
  'options.watercolor',
  'options.other'
);

insert into public.form_texts (key, en_text, he_text)
values
  ('brand', 'Zen House Tattoo', 'Zen House Tattoo'),
  ('intro', 'Design request', 'בקשת עיצוב'),
  ('step', 'Step', 'שלב'),
  ('of', 'of', 'מתוך'),
  ('back', 'Back', 'חזרה'),
  ('next', 'Next', 'הבא'),
  ('quote', 'Send request', 'שליחת פנייה'),
  ('clearAll', 'Clear marks', 'ניקוי סימונים'),
  ('delete', 'Delete', 'מחיקה'),
  ('mark', 'Mark', 'סימון'),
  ('marksEmpty', 'No marks yet.', 'אין סימונים עדיין.'),
  ('referenceImages', 'Reference images', 'תמונות השראה'),
  ('maxReferenceImages', 'Up to 4 images', 'עד 4 תמונות'),
  ('maxPlacementBoxes', 'Up to 3 marks', 'עד 3 סימונים'),
  ('minIdeaCharacters', 'Minimum 20 characters', 'מינימום 20 תווים'),
  ('moreStyles', 'More styles', 'עוד סגנונות'),
  ('showLessStyles', 'Show less', 'הצג פחות'),
  ('submitting', 'Redirecting you to WhatsApp...', 'מעבירים אתכם לוואטסאפ...'),
  ('steps.name.title', 'Welcome', 'ברוכים הבאים'),
  ('steps.name.note', 'So we can send you a quote for the perfect tattoo, please fill in the details below.', 'כדי שנוכל לשלוח לכם הצעת מחיר לקעקוע המושלם אנא מלאו את הפרטים הבאים'),
  ('steps.name.placeholders.fullName', 'Full name', 'שם מלא'),
  ('steps.name.placeholders.email', 'Email', 'אימייל'),
  ('steps.name.placeholders.phone', 'WhatsApp number', 'מספר טלפון'),
  ('steps.description.title', 'Tell us about the tattoo', 'ספרו לנו על הקעקוע'),
  ('steps.description.ideaLabel', 'Tattoo description', 'תיאור הקעקוע'),
  ('steps.description.uploadLabel', 'Up to 4 images allowed', 'ניתן להעלות עד 4 תמונות בלבד'),
  ('steps.description.placeholder', 'Describe the idea, size, mood or important details...', 'תארו בקצרה את הרעיון, הגודל, האווירה או פרטים חשובים...'),
  ('steps.color.title', 'Which do you prefer?', 'מה תעדיפו?'),
  ('steps.style.title', 'What style speaks to you?', 'איזה סטייל מדבר אליכם?'),
  ('steps.bodyReference.title', 'Which model should we place the tattoo on?', 'על איזה מודל נמקם את הקעקוע?'),
  ('steps.generalZone.title', 'Choose a category', 'בחירת אזור'),
  ('steps.specificZone.title', 'Please choose the area', 'אנא בחרו את האיזור'),
  ('steps.placement.title', 'Mark the tattoo placement', 'סימון מיקום הקעקוע'),
  ('steps.placement.note', 'Please mark the area where you''d like the tattoo.', 'אנא סמנו את האיזור שבו תרצו את הקעקוע'),
  ('steps.timing.title', 'When are you planning to get tattooed?', 'מתי תכננתם להתקעקע?'),
  ('steps.contactTime.title', 'What is the best time to reach you?', 'מתי נוח לכם לדבר?'),
  ('steps.contactTime.note', 'You can choose more than one option.', 'אפשר לבחור יותר מאפשרות אחת.'),
  ('steps.hasTattoos.title', 'Do you already have tattoos?', 'האם התקעקעתם בעבר?'),
  ('options.blackGrey', 'Black & grey', 'שחור ואפור'),
  ('options.color', 'Color', 'צבע'),
  ('options.now', 'ASAP', 'בהקדם האפשרי'),
  ('options.weeks', 'Next weeks', 'בשבועיים הקרובים'),
  ('options.month', 'Next month', 'בחודש הקרוב'),
  ('options.dontCare', 'I don''t care', 'לא משנה לי'),
  ('options.morning', 'Morning ☀', '☀ בוקר'),
  ('options.afternoon', 'Afternoon ●', '● צהריים'),
  ('options.night', 'Night ☾', '☾ ערב'),
  ('options.yes', 'Yes', 'כן'),
  ('options.no', 'No', 'לא'),
  ('errors.name', 'Add your name, email and WhatsApp number.', 'יש למלא שם, אימייל ומספר WhatsApp.'),
  ('errors.description', 'Write at least 20 characters.', 'יש לכתוב לפחות 20 תווים.'),
  ('errors.style', 'Choose a style.', 'יש לבחור סגנון.'),
  ('errors.color', 'Choose a color option.', 'יש לבחור צבע.'),
  ('errors.bodyReference', 'Choose a body reference.', 'יש לבחור ייחוס גוף.'),
  ('errors.generalZone', 'Choose a body area.', 'יש לבחור אזור בגוף.'),
  ('errors.specificZone', 'Choose a specific view.', 'יש לבחור זווית ספציפית.'),
  ('errors.placement', 'Draw at least one placement mark.', 'יש לסמן לפחות מיקום אחד.'),
  ('errors.timing', 'Choose when you want to do it.', 'יש לבחור מתי תרצו לעשות את הקעקוע.'),
  ('errors.contactTime', 'Choose the best time to contact you.', 'יש לבחור זמן נוח ליצירת קשר.'),
  ('errors.hasTattoos', 'Choose yes or no.', 'יש לבחור כן או לא.'),
  ('errors.default', 'Complete this step to continue.', 'יש להשלים את השלב כדי להמשיך.'),
  ('whatsapp.hello', 'Hi ZenHouse! I want to request a tattoo.', 'שלום ZenHouse! אשמח לקבל הצעת מחיר לקעקוע.'),
  ('whatsapp.name', 'Name', 'שם'),
  ('whatsapp.email', 'Email', 'אימייל'),
  ('whatsapp.phone', 'Phone', 'טלפון'),
  ('whatsapp.bodyReference', 'Body reference', 'ייחוס גוף'),
  ('whatsapp.hasTattoos', 'Has tattoos?', 'יש קעקועים?'),
  ('whatsapp.generalZone', 'Category', 'אזור'),
  ('whatsapp.specificZone', 'View', 'זווית'),
  ('whatsapp.placement', 'Placement', 'סימון'),
  ('whatsapp.style', 'Style', 'סגנון'),
  ('whatsapp.color', 'Color', 'צבע'),
  ('whatsapp.idea', 'Idea', 'רעיון'),
  ('whatsapp.referenceImages', 'Reference images', 'תמונות השראה'),
  ('whatsapp.timing', 'When', 'מתי'),
  ('whatsapp.contactTime', 'Contact time', 'זמן קשר')
on conflict (key) do update
set
  en_text = excluded.en_text,
  he_text = excluded.he_text,
  updated_at = now();
